name: .NET Docker Build Workflow (Local Only)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image (Local Only)
        run: |
          docker build -t cf-application:${{ github.sha }} -f CFWebAPI/Dockerfile CFWebAPI
          docker images cf-application:${{ github.sha }}
