name: Build & Deploy to Local Docker

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy-local:
    runs-on: [ self-hosted ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dump workspace tree
        run: ls -R .

      - name: Build Docker image locally
        run: docker build -t cfwebapi:latest -f CFWebAPI/Dockerfile CFWebAPI

      - name: (Re)start container
        run: |
          if docker ps -q --filter "name=cfwebapi-local"; then
            docker stop cfwebapi-local && docker rm cfwebapi-local
          fi
          docker run -d --name cfwebapi-local -p 5000:80 cfwebapi:latest
