name: Build & Deploy to Local Docker

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy-local:
    runs-on: [ self-hosted ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image locally
        # explicit pwsh so we can run a single-line build command
        shell: pwsh
        run: |
          docker build -t cfwebapi:latest -f CFWebAPI/Dockerfile CFWebAPI

      - name: (Re)start container
        shell: pwsh
        run: |
          # if it exists, stop & remove
          if (docker ps -aq -f "name=cfwebapi-local") {
            docker stop cfwebapi-local
            docker rm  cfwebapi-local
          }
          # run fresh container
          docker run -d --name cfwebapi-local -p 5000:80 cfwebapi:latest
