name: Build & Deploy to Local Docker

on:
  workflow_dispatch:
  push:
    branches: [master ]
  pull_request:
    branches: [master ]

jobs:
  deploy-local:
    runs-on: [ self-hosted ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dump workspace tree
        run: ls -R .

      - name: Build Docker image locally
        run: docker build -t cfwebapi:latest -f CFWebAPI/Dockerfile .

      - name: (Re)start container
        shell: powershell
        run: |
          # get any existing container ID by name
          $existing = docker ps -aq -f "name=cfwebapi-local"
          if ($existing) {
            Write-Host "Stopping & removing existing container..."
            docker stop cfwebapi-local
            docker rm cfwebapi-local
          }
          Write-Host "Starting new container..."
          docker run -d --name cfwebapi-local -p 5000:80 cfwebapi:latest
