name: .NET Docker Build and Deploy Locally

on:
  workflow_dispatch: # Manually trigger the workflow
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t cfwebapi:local -f CFWebAPI/Dockerfile CFWebAPI
          docker save cfwebapi:local -o cfwebapi_local.tar

      - name: Upload Docker Image as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: cfwebapi_local_image
          path: cfwebapi_local.tar
