name: Build & Deploy to Local Docker

# you can still trigger on pushes/PRs or manually
on:
  workflow_dispatch:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]

jobs:
  deploy-local:
    # target your self-hosted runner
    runs-on: [ self-hosted ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Ensure Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image locally
        run: |
          # build — the Docker daemon on this runner is your local Docker
          docker build \
            -t cfwebapi:latest \
            -f CFWebAPI/Dockerfile \
            CFWebAPI

      - name: (Re)start container
        run: |
          # stop & remove any running container
          docker stop cfwebapi-local || true
          docker rm cfwebapi-local  || true
          # run new one
          docker run -d \
            --name cfwebapi-local \
            -p 5000:80 \
            cfwebapi:latest
