-   id: ecr-publish
    uses: bitovi/github-actions-ecr-publish@v0.1.0
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_default_region: us-east-1
        aws_ecr_repo_name: hello-repo
